ffk_botanique:
    pattern:  /botanique
    defaults: { _controller: FfkBotaniqueBundle:Botanic:index }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media